### ISSUE TITLE
Support for Spanned<T>

### ISSUE THREAD

**Issue by gilescope** [dtolnay/serde-untagged#5]
I'm trying to see if we can make cargo spit out file and line numbers when it encounters errors. It uses UntaggedEnum to parse toml here:

https://github.com/rust-lang/cargo/blob/69255bb10de7f74511b5cef900a9d102247b6029/crates/cargo-util-schemas/src/manifest.rs#L565

It would be really helpful if UntaggedEnum had a `spanned` feature that allowed `Spanned<String>` and `Spanned<Map<_,_>>` etc to be deserialised.

Does this seem a sensible route forwards?

**Comment by dtolnay** [comment]
It should already be possible to deserialize `Spanned<TomlDependency>` just using the code in your link.

Assuming https://github.com/toml-rs/toml/pull/664 is accepted, you could then transpose it to put `Spanned` inside the enum, using the example code in that PR.

I don't know of any other way that one could directly deserialize an untagged enum containing `Spanned`.

**Comment by epage** [comment]
@gilescope That would be a large invasive change to cargo that you should probably coordinate with the cargo team before proceeding.  In fact, @Muscraft is already working on this though using an alternative design (not using `Spanned`)
